spring:
  config:
    activate:
      on-profile: dev
  application:
    name: auth-server

eureka:
  hostname: http://localhost:8761
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_URI: ${eureka.hostname}/eureka}
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    fetchRegistry: true
  instance:
    preferIpAddress: true
    homePageUrl: ${eureka.hostname}
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
