CREATE TABLE DEPARTMENT (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE JOB (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    DESCRIPTION TEXT,
    CONSTRAINT FK_JOB_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    DEPARTMENT_ID BIGINT,
    JOB_ID BIGINT,
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID) ON DELETE SET NULL,
    CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB(ID) ON DELETE SET NULL
);

CREATE TABLE EMPLOYEE_CERTIFICATE (
    ID BIGSERIAL PRIMARY KEY,
    EMPLOYEE_ID BIGINT NOT NULL,
    CERTIFICATE_NAME VARCHAR(255) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE,
    ISSUED_BY VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_EMPLOYEE_CERTIFICATE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYMENT_HISTORY (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    JOB_NAME VARCHAR(255) NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    EMPLOYEE_ID BIGINT NOT NULL,
    CONSTRAINT FK_EMPLOYMENT_HISTORY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE_AGREEMENT (
    ID BIGSERIAL PRIMARY KEY,
    SALARY NUMERIC(19,2) NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    STATUS VARCHAR(10) NOT NULL,
    AGREEMENT_TYPE VARCHAR(50) NOT NULL,
    PAYMENT_TYPE VARCHAR(50) NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_EMPLOYEE_AGREEMENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT_RANGE (
    ID BIGSERIAL PRIMARY KEY,
    MIN_SALARY NUMERIC(19,2) NOT NULL,
    MAX_SALARY NUMERIC(19,2) NOT NULL,
    JOB_ID BIGINT NOT NULL,
    EMPLOYMENT_AGREEMENT_TYPE VARCHAR(50) NOT NULL,
    FISCAL_YEAR INTEGER NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_PAYMENT_RANGE_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB(ID) ON DELETE CASCADE
);

CREATE TABLE CLAUSE (
    id BIGSERIAL PRIMARY KEY,
    clause_type VARCHAR(255),
    clause_title VARCHAR(255),
    clause_description TEXT
);

CREATE TABLE employee_agreement_clause (
    id BIGSERIAL PRIMARY KEY,
    start_date DATE,
    end_date DATE,
    employee_agreement_clause_id BIGINT NOT NULL,
    clause_id BIGINT NOT NULL,
    CONSTRAINT fk_employee_agreement
        FOREIGN KEY (employee_agreement_clause_id)
        REFERENCES employee_agreement(id),
    CONSTRAINT fk_clause
        FOREIGN KEY (clause_id)
        REFERENCES clause(id)
);

