CREATE TABLE DEPARTMENT (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE JOB (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    DESCRIPTION TEXT,
    CONSTRAINT FK_JOB_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    JOB_ID BIGINT NOT NULL,
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID) ON DELETE SET NULL,
    CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB(ID) ON DELETE SET NULL
);

CREATE TABLE EMPLOYEE_CERTIFICATE (
    ID BIGSERIAL PRIMARY KEY,
    EMPLOYEE_ID BIGINT NOT NULL,
    CERTIFICATE_NAME VARCHAR(255) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE,
    ISSUED_BY VARCHAR(255),
    CONSTRAINT FK_EMPLOYEE_CERTIFICATE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYMENT_HISTORY (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    JOB_NAME VARCHAR(255) NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    EMPLOYEE_ID BIGINT NOT NULL,
    CONSTRAINT FK_EMPLOYMENT_HISTORY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE_AGREEMENT (
    ID BIGSERIAL PRIMARY KEY,
    SALARY NUMERIC(19,2) NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    STATUS VARCHAR(10) NOT NULL,
    AGREEMENT_TYPE VARCHAR(50) NOT NULL,
    PAYMENT_TYPE VARCHAR(50) NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    CONSTRAINT FK_EMPLOYEE_AGREEMENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);
