-- Payment ranges for IT Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (3600, 6000, 1, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (9600, 14400, 2, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (7200, 12000, 3, 'EMPLOYMENT', 2024);

-- Payment ranges for IT Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (4680, 7800, 1, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (12480, 18720, 2, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (9360, 15600, 3, 'B2B', 2024);

-- Payment ranges for PRODUCT Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (8400, 13200, 4, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (7800, 12600, 5, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (6600, 11400, 6, 'EMPLOYMENT', 2024);

-- Payment ranges for PRODUCT Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (10920, 17160, 4, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (10140, 16380, 5, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (8580, 14820, 6, 'B2B', 2024);

-- Payment ranges for SALES Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (4800, 9600, 7, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (10800, 18000, 8, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (6000, 10800, 9, 'EMPLOYMENT', 2024);

-- Payment ranges for SALES Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (6240, 12480, 7, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (14040, 23400, 8, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (7800, 14040, 9, 'B2B', 2024);

-- Payment ranges for ACCOUNTING Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (3600, 6000, 10, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (9600, 14400, 11, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (12000, 18000, 12, 'EMPLOYMENT', 2024);

-- Payment ranges for ACCOUNTING Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (4680, 7800, 10, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (12480, 18720, 11, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (15600, 23400, 12, 'B2B', 2024);

-- Payment ranges for HR Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (6000, 9600, 13, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (10800, 15600, 14, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (5400, 8400, 15, 'EMPLOYMENT', 2024);

-- Payment ranges for HR Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (7800, 12480, 13, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (14040, 20280, 14, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, YEAR)
VALUES (7020, 10920, 15, 'B2B', 2024);
