auth-server: http://localhost:9000

spring:
  graphql:
    datetime:
      scalars:
        zone-conversion-enabled: true
        local-date:
          format: dd-MM-yyyy
        local-date-time:
          format: yyyy-MM-dd'T'HH:mm:ss
    graphiql:
      enabled: true
  application:
    name: graphql-api
  datasource:
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: auth-server
          jwk-set-uri: ${auth-server}/jwks

rsa:
  public-key: classpath:certs/public_key.pem
server:
  port: 8765

cache:
  refresh:
    interval: 3600000 #1h

management:
  endpoints:
    web:
      exposure:
        include: health,info
