auth-server: http://localhost:9000

spring:
  application:
    name: employee-server
  datasource:
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: auth-server
          jwk-set-uri: ${auth-server}/jwks

rsa:
  public-key: classpath:certs/public_key.pem
server:
  port: 8082

cache:
  refresh:
    interval: 3600000 #1h

management:
  endpoints:
    web:
      exposure:
        include: health,info
