spring:
  application:
    name: employee-server
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres-cma
    username: postgres
    password: marcin123
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/jwks

logging:
  level:
    org.springframework.security: DEBUG
rsa:
  public-key: classpath:certs/public_key.pem
server:
  port: 8082

eureka:
  hostname: http://localhost:8761
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_URI: ${eureka.hostname}/eureka}
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    fetchRegistry: true
  instance:
    preferIpAddress: true
    homePageUrl: ${eureka.hostname}
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health