auth-server: http://auth-server:9000

spring:
  config:
    activate:
      on-profile: docker
  application:
    name: employee-server
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: marcin123
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: auth-server
          jwk-set-uri: ${auth-server}/jwks

logging:
  level:
    org.springframework.security: DEBUG
    com.gminds.employee_service: DEBUG
rsa:
  public-key: classpath:certs/public_key.pem
server:
  port: 8082

cache:
  refresh:
    interval: 3600000 #1h

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  hostname: http://eureka-server:8761
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_URI: ${eureka.hostname}/eureka}
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    fetchRegistry: true
  instance:
    preferIpAddress: true
    homePageUrl: ${eureka.hostname}
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health