CREATE TABLE EMPLOYEE_USER (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    roles VARCHAR(100) NOT NULL
);

INSERT INTO employee_user (username, password, roles)
VALUES ('user', '$2a$10$dVDjEBKps/RWfGoaY8I63.afntCAwNUqbIbhOF7L/Ioery.0wH9OO', 'ROLE_USER');


CREATE TABLE DEPARTMENT (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE JOB (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    DESCRIPTION TEXT,
    CONSTRAINT FK_JOB_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    DEPARTMENT_ID BIGINT,
    JOB_ID BIGINT,
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID) ON DELETE SET NULL,
    CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB(ID) ON DELETE SET NULL
);

CREATE TABLE EMPLOYEE_CERTIFICATE (
    ID BIGSERIAL PRIMARY KEY,
    EMPLOYEE_ID BIGINT NOT NULL,
    CERTIFICATE_NAME VARCHAR(255) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE,
    ISSUED_BY VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_EMPLOYEE_CERTIFICATE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYMENT_HISTORY (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    JOB_NAME VARCHAR(255) NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    EMPLOYEE_ID BIGINT NOT NULL,
    CONSTRAINT FK_EMPLOYMENT_HISTORY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE_AGREEMENT (
    ID BIGSERIAL PRIMARY KEY,
    SALARY NUMERIC(19,2) NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    STATUS VARCHAR(10) NOT NULL,
    AGREEMENT_TYPE VARCHAR(50) NOT NULL,
    PAYMENT_TYPE VARCHAR(50) NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_EMPLOYEE_AGREEMENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT_RANGE (
    ID BIGSERIAL PRIMARY KEY,
    MIN_SALARY NUMERIC(19,2) NOT NULL,
    MAX_SALARY NUMERIC(19,2) NOT NULL,
    JOB_ID BIGINT NOT NULL,
    EMPLOYMENT_AGREEMENT_TYPE VARCHAR(50) NOT NULL,
    FISCAL_YEAR INTEGER NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_PAYMENT_RANGE_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB(ID) ON DELETE CASCADE
);


INSERT INTO DEPARTMENT (NAME, DESCRIPTION) VALUES ('IT', 'Information Technology department');
INSERT INTO DEPARTMENT (NAME, DESCRIPTION) VALUES ('PRODUCT', 'Product development and management department');
INSERT INTO DEPARTMENT (NAME, DESCRIPTION) VALUES ('SALES', 'Sales and business development department');
INSERT INTO DEPARTMENT (NAME, DESCRIPTION) VALUES ('ACCOUNTING', 'Accounting and finance department');
INSERT INTO DEPARTMENT (NAME, DESCRIPTION) VALUES ('HR', 'Human Resources department');


-- Inserty dla tabeli JOB
-- IT Department Jobs
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Junior Developer', 1, 'Entry-level software developer');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Senior Developer', 1, 'Experienced software developer');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('DevOps Engineer', 1, 'Responsible for IT infrastructure and automation');

-- PRODUCT Department Jobs
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Product Manager', 2, 'Oversees product development and strategy');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Product Owner', 2, 'Defines product vision and manages product backlog');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('UX Designer', 2, 'Focuses on user experience and interface design');

-- SALES Department Jobs
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Sales Executive', 3, 'Handles sales and client acquisition');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Sales Manager', 3, 'Manages sales team and strategies');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Account Manager', 3, 'Maintains client relationships and sales operations');

-- ACCOUNTING Department Jobs
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Junior Accountant', 4, 'Handles basic accounting tasks and entries');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Senior Accountant', 4, 'Oversees financial reporting and accounting procedures');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Finance Manager', 4, 'Manages financial planning and analysis');

-- HR Department Jobs
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('HR Specialist', 5, 'Manages recruitment and employee relations');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('HR Manager', 5, 'Oversees HR policies and department operations');
INSERT INTO JOB (TITLE, DEPARTMENT_ID, DESCRIPTION) VALUES ('Recruitment Coordinator', 5, 'Coordinates recruitment processes and activities');


-- Payment ranges for IT Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (3600, 6000, 1, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (9600, 14400, 2, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (7200, 12000, 3, 'EMPLOYMENT', 2024);

-- Payment ranges for IT Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (4680, 7800, 1, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (12480, 18720, 2, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (9360, 15600, 3, 'B2B', 2024);

-- Payment ranges for PRODUCT Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (8400, 13200, 4, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (7800, 12600, 5, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (6600, 11400, 6, 'EMPLOYMENT', 2024);

-- Payment ranges for PRODUCT Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (10920, 17160, 4, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (10140, 16380, 5, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (8580, 14820, 6, 'B2B', 2024);

-- Payment ranges for SALES Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (4800, 9600, 7, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (10800, 18000, 8, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (6000, 10800, 9, 'EMPLOYMENT', 2024);

-- Payment ranges for SALES Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (6240, 12480, 7, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (14040, 23400, 8, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (7800, 14040, 9, 'B2B', 2024);

-- Payment ranges for ACCOUNTING Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (3600, 6000, 10, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (9600, 14400, 11, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (12000, 18000, 12, 'EMPLOYMENT', 2024);

-- Payment ranges for ACCOUNTING Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (4680, 7800, 10, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (12480, 18720, 11, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (15600, 23400, 12, 'B2B', 2024);

-- Payment ranges for HR Department Jobs (Employment)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (6000, 9600, 13, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (10800, 15600, 14, 'EMPLOYMENT', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (5400, 8400, 15, 'EMPLOYMENT', 2024);

-- Payment ranges for HR Department Jobs (B2B)
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (7800, 12480, 13, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (14040, 20280, 14, 'B2B', 2024);
INSERT INTO PAYMENT_RANGE (MIN_SALARY, MAX_SALARY, JOB_ID, EMPLOYMENT_AGREEMENT_TYPE, FISCAL_YEAR)
VALUES (7020, 10920, 15, 'B2B', 2024);
